# Generated by Django 5.1.11 on 2026-04-24 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant_core', '0001_initial'),
        ('catalog', '0001_initial'),
        ('prices', '0034_supplierproduct_catalog_perfume_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualLinkDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(choices=[('approve_perfume', 'Approve perfume'), ('approve_variant', 'Approve variant'), ('reject', 'Reject'), ('exclude', 'Exclude')], db_index=True, max_length=40)),
                ('reason', models.TextField(blank=True)),
                ('apply_to_similar', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('perfume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.perfume')),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_decisions', to='prices.supplierproduct')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.perfumevariant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MatchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_key', models.CharField(db_index=True, max_length=500, unique=True)),
                ('canonical_name', models.CharField(db_index=True, max_length=255)),
                ('concentration', models.CharField(blank=True, db_index=True, max_length=80)),
                ('audience_hint', models.CharField(blank=True, db_index=True, max_length=80)),
                ('size_ml', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=7, null=True)),
                ('packaging', models.CharField(blank=True, db_index=True, max_length=80)),
                ('variant_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('excluded', 'Excluded'), ('conflict', 'Conflict')], db_index=True, default='open', max_length=20)),
                ('confidence', models.PositiveSmallIntegerField(db_index=True, default=50)),
                ('candidate_perfume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.perfume')),
                ('candidate_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.perfumevariant')),
                ('normalized_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand')),
            ],
            options={
                'ordering': ('status', '-confidence', 'canonical_name'),
            },
        ),
        migrations.CreateModel(
            name='LinkSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('reasoning', models.TextField(blank=True)),
                ('rules_used_json', models.JSONField(blank=True, default=list)),
                ('uncertainties_json', models.JSONField(blank=True, default=list)),
                ('source_engine', models.CharField(db_index=True, default='mock', max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('excluded', 'Excluded')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('research_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistant_core.researchjob')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('suggested_perfume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.perfume')),
                ('suggested_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.perfumevariant')),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_link_suggestions', to='prices.supplierproduct')),
                ('match_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_suggestions', to='assistant_linking.matchgroup')),
            ],
            options={
                'ordering': ('-confidence', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ParsedSupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_name', models.TextField()),
                ('normalized_text', models.TextField(db_index=True)),
                ('detected_brand_text', models.CharField(blank=True, max_length=255)),
                ('product_name_text', models.CharField(blank=True, db_index=True, max_length=255)),
                ('concentration', models.CharField(blank=True, db_index=True, max_length=80)),
                ('size_ml', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=7, null=True)),
                ('raw_size_text', models.CharField(blank=True, max_length=80)),
                ('supplier_gender_hint', models.CharField(blank=True, db_index=True, max_length=80)),
                ('packaging', models.CharField(blank=True, db_index=True, max_length=80)),
                ('variant_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('is_tester', models.BooleanField(db_index=True, default=False)),
                ('is_sample', models.BooleanField(db_index=True, default=False)),
                ('is_travel', models.BooleanField(db_index=True, default=False)),
                ('is_set', models.BooleanField(db_index=True, default=False)),
                ('modifiers', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('confidence', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('parser_version', models.CharField(default='deterministic-v1', max_length=40)),
                ('locked_by_human', models.BooleanField(db_index=True, default=False)),
                ('last_parsed_at', models.DateTimeField(blank=True, null=True)),
                ('normalized_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand')),
                ('supplier_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_parse', to='prices.supplierproduct')),
            ],
            options={
                'ordering': ('supplier_product__supplier__name', 'supplier_product__name'),
            },
        ),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias_text', models.CharField(db_index=True, max_length=255)),
                ('canonical_text', models.CharField(db_index=True, max_length=255)),
                ('concentration', models.CharField(blank=True, max_length=80)),
                ('audience', models.CharField(blank=True, max_length=80)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.IntegerField(db_index=True, default=100)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_aliases', to='catalog.brand')),
                ('perfume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_aliases', to='catalog.perfume')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_aliases', to='prices.supplier')),
            ],
            options={
                'ordering': ('supplier__name', 'priority', 'alias_text'),
            },
        ),
        migrations.CreateModel(
            name='BrandAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias_text', models.CharField(db_index=True, max_length=255)),
                ('normalized_alias', models.CharField(db_index=True, max_length=255)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.IntegerField(db_index=True, default=100)),
                ('is_regex', models.BooleanField(db_index=True, default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.brand')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_aliases', to='prices.supplier')),
            ],
            options={
                'ordering': ('supplier__name', 'priority', 'alias_text'),
                'constraints': [models.UniqueConstraint(fields=('alias_text', 'supplier', 'brand'), name='uniq_assistant_brand_alias')],
            },
        ),
        migrations.CreateModel(
            name='MatchGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('excluded', 'Excluded'), ('split', 'Split'), ('conflict', 'Conflict')], db_index=True, default='member', max_length=20)),
                ('match_score', models.PositiveSmallIntegerField(db_index=True, default=50)),
                ('reasoning', models.TextField(blank=True)),
                ('match_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assistant_linking.matchgroup')),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_group_items', to='prices.supplierproduct')),
                ('parsed_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistant_linking.parsedsupplierproduct')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('match_group', 'supplier_product'), name='uniq_assistant_group_item')],
            },
        ),
    ]
