# Generated by Django 5.1.11 on 2026-04-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_linking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productalias',
            name='excluded_terms',
            field=models.TextField(blank=True),
        ),
    ]
