# Generated by Django 5.1.11 on 2026-04-25

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_ALIASES = (
    ("extrait de parfum", "Extrait de Parfum"),
    ("extrait", "Extrait de Parfum"),
    ("eau de parfum", "Eau de Parfum"),
    ("edp", "Eau de Parfum"),
    ("парфюмированная вода", "Eau de Parfum"),
    ("парфюмерная вода", "Eau de Parfum"),
    ("eau de toilette", "Eau de Toilette"),
    ("edt", "Eau de Toilette"),
    ("eau de cologne", "Eau de Cologne"),
    ("edc", "Eau de Cologne"),
    ("parfum", "Parfum"),
    ("perfume oil", "Perfume Oil"),
)


def seed_default_concentration_aliases(apps, schema_editor):
    ConcentrationAlias = apps.get_model("assistant_linking", "ConcentrationAlias")
    for alias_text, concentration in DEFAULT_ALIASES:
        ConcentrationAlias.objects.get_or_create(
            alias_text=alias_text,
            supplier=None,
            concentration=concentration,
            defaults={
                "normalized_alias": alias_text,
                "active": True,
                "priority": 100,
                "is_regex": False,
            },
        )


def remove_default_concentration_aliases(apps, schema_editor):
    ConcentrationAlias = apps.get_model("assistant_linking", "ConcentrationAlias")
    for alias_text, concentration in DEFAULT_ALIASES:
        ConcentrationAlias.objects.filter(alias_text=alias_text, supplier=None, concentration=concentration).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("assistant_linking", "0003_expand_concentration_labels"),
        ("prices", "0034_supplierproduct_catalog_perfume_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcentrationAlias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("concentration", models.CharField(db_index=True, max_length=80)),
                ("alias_text", models.CharField(db_index=True, max_length=255)),
                ("normalized_alias", models.CharField(db_index=True, max_length=255)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("priority", models.IntegerField(db_index=True, default=100)),
                ("is_regex", models.BooleanField(db_index=True, default=False)),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concentration_aliases",
                        to="prices.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ("supplier__name", "priority", "alias_text"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("alias_text", "supplier", "concentration"),
                        name="uniq_assistant_concentration_alias",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_default_concentration_aliases, remove_default_concentration_aliases),
    ]
