# Generated by Codex on 2026-04-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant_linking", "0004_concentrationalias"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualLinkDecisionAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("previous_pk", models.PositiveBigIntegerField(db_index=True)),
                ("previous_decision_json", models.JSONField()),
                ("replaced_at", models.DateTimeField(auto_now_add=True)),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replacement_audits",
                        to="assistant_linking.manuallinkdecision",
                    ),
                ),
            ],
            options={
                "ordering": ("-replaced_at",),
            },
        ),
    ]
