# Generated by Django 5.2.13 on 2026-04-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant_linking", "0010_seed_mugler_angel_etoile_aliases"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchgroup",
            name="collection_name",
            field=models.CharField(blank=True, db_index=True, max_length=180),
        ),
        migrations.AddField(
            model_name="parsedsupplierproduct",
            name="collection_name",
            field=models.CharField(blank=True, db_index=True, max_length=180),
        ),
        migrations.AddField(
            model_name="productalias",
            name="collection_name",
            field=models.CharField(blank=True, db_index=True, max_length=180),
        ),
    ]
