# Generated by Django 5.2.13 on 2026-04-29 13:04

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_linking', '0027_seed_dunhill_desire_red_alias'),
        ('catalog', '0002_expand_concentration_labels'),
        ('prices', '0045_remove_emailattachmentdiagnostic_prices_diag_mailbox_uid_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parsedsupplierproduct',
            index=django.contrib.postgres.indexes.GinIndex(fields=['modifiers'], name='alink_parse_modifiers_gin'),
        ),
    ]
