# Generated by Django 5.2.13 on 2026-05-02 15:42

import django.db.models.deletion
import re
import unicodedata
from django.db import migrations, models
from django.utils.text import slugify


def normalized_collection_name(value):
    text = unicodedata.normalize("NFKD", value or "")
    text = "".join(char for char in text if not unicodedata.combining(char))
    text = text.replace("&", " and ").lower()
    return re.sub(r"\s+", " ", re.sub(r"[^\w]+", " ", text)).strip()


def unique_collection_slug(Collection, brand_id, value):
    base = slugify(value or "") or "collection"
    slug = base
    counter = 2
    while Collection.objects.filter(brand_id=brand_id, slug=slug).exists():
        suffix = f"-{counter}"
        slug = f"{base[:240 - len(suffix)]}{suffix}"
        counter += 1
    return slug


def backfill_fragrantica_collections(apps, schema_editor):
    Brand = apps.get_model("catalog", "Brand")
    Collection = apps.get_model("catalog", "Collection")
    FragranticaProduct = apps.get_model("assistant_linking", "FragranticaProduct")
    brands_by_name = {brand.name.lower(): brand for brand in Brand.objects.all()}
    collections_by_key = {
        (collection.brand_id, collection.normalized_name): collection
        for collection in Collection.objects.all()
    }
    fragrantica_products = FragranticaProduct.objects.exclude(collection_name="")
    for product in fragrantica_products.iterator():
        brand = brands_by_name.get((product.brand_name or "").lower())
        if not brand:
            continue
        normalized_name = normalized_collection_name(product.collection_name)
        if not normalized_name:
            continue
        key = (brand.pk, normalized_name)
        collection = collections_by_key.get(key)
        if collection is None:
            collection = Collection.objects.create(
                brand_id=brand.pk,
                name=product.collection_name,
                normalized_name=normalized_name,
                slug=unique_collection_slug(
                    Collection, brand.pk, product.collection_name
                ),
            )
            collections_by_key[key] = collection
        FragranticaProduct.objects.filter(pk=product.pk).update(
            collection_id=collection.pk
        )


class Migration(migrations.Migration):

    dependencies = [
        ("assistant_linking", "0032_disable_seeded_woodbox_variant_type"),
        ("catalog", "0003_collection_perfume_collection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fragranticaproduct",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fragrantica_products",
                to="catalog.collection",
            ),
        ),
        migrations.RunPython(
            backfill_fragrantica_collections, migrations.RunPython.noop
        ),
    ]
