# Generated by Django 5.2.13 on 2026-05-05 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant_linking", "0052_fragranticaproductlink"),
        ("catalog", "0003_collection_perfume_collection_and_more"),
        ("prices", "0045_remove_emailattachmentdiagnostic_prices_diag_mailbox_uid_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("fragrantica_link_rerank", "Fragrantica link rerank"),
                            ("normalization_review", "Normalization review"),
                            ("kb_suggestion", "Knowledge/rule suggestion"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("input_hash", models.CharField(db_index=True, max_length=64)),
                ("prompt_version", models.CharField(db_index=True, max_length=40)),
                ("model_name", models.CharField(blank=True, max_length=80)),
                (
                    "confidence",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("input_context_json", models.JSONField(blank=True, default=dict)),
                ("recommendation_json", models.JSONField(blank=True, default=dict)),
                ("reasoning", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fragrantica_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_recommendations",
                        to="assistant_linking.fragranticaproduct",
                    ),
                ),
                (
                    "parsed_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_recommendations",
                        to="assistant_linking.parsedsupplierproduct",
                    ),
                ),
                (
                    "perfume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_ai_recommendations",
                        to="catalog.perfume",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_recommendations",
                        to="prices.supplierproduct",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["task_type", "status"], name="alink_ai_task_status_idx"
                    ),
                    models.Index(
                        fields=["input_hash", "task_type"],
                        name="alink_ai_input_task_idx",
                    ),
                ],
            },
        ),
    ]
