# Generated by Django 5.2.13 on 2026-05-05 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant_linking", "0053_airecommendation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AILearningProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposal_type",
                    models.CharField(
                        choices=[
                            ("fragrantica_link_review", "Fragrantica link review"),
                            ("product_alias", "Product alias"),
                            ("brand_alias", "Brand alias"),
                            ("global_rule", "Global rule"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("applied", "Applied"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("summary", models.TextField(blank=True)),
                ("proposed_action_json", models.JSONField(blank=True, default=dict)),
                ("evidence_json", models.JSONField(blank=True, default=dict)),
                ("impact_json", models.JSONField(blank=True, default=dict)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_recommendation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_proposal",
                        to="assistant_linking.airecommendation",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["proposal_type", "status"],
                        name="alink_ai_prop_type_status",
                    )
                ],
            },
        ),
    ]
