# Generated by Django 5.2.13 on 2026-05-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant_linking", "0054_ailearningproposal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ailearningproposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("applied", "Applied"),
                    ("reverted", "Reverted"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
