# ruff: noqa: F401

from .views_records import (
    ExchangeRateCreateView,
    ExchangeRateDeleteView,
    ExchangeRateListView,
    ExchangeRateUpdateView,
    ImportBatchCreateView,
    ImportBatchDeleteView,
    ImportBatchListView,
    ImportBatchUpdateView,
    ImportFileCreateView,
    ImportFileDeleteView,
    ImportFileListView,
    ImportFileUpdateView,
    PriceSnapshotCreateView,
    PriceSnapshotDeleteView,
    PriceSnapshotListView,
    PriceSnapshotUpdateView,
    StockSnapshotCreateView,
    StockSnapshotDeleteView,
    StockSnapshotListView,
    StockSnapshotUpdateView,
)
from .views_accounts import (
    UserCreateView,
    UserDeleteView,
    UserGroupCreateView,
    UserGroupDeleteView,
    UserGroupListView,
    UserGroupUpdateView,
    UserListView,
    UserProfileUpdateView,
    UserUpdateView,
)
from .views_suppliers import (
    SupplierCreateView,
    SupplierDeleteView,
    SupplierDetailView,
    SupplierListView,
    SupplierUpdateView,
)
from .views_supplier_overview import SupplierOverviewView
from .views_import_config import (
    MailboxCreateView,
    MailboxDeleteView,
    MailboxListView,
    MailboxUpdateView,
    SupplierFileMappingCreateView,
    SupplierFileMappingDeleteView,
    SupplierFileMappingListView,
    SupplierFileMappingUpdateView,
    SupplierMailboxRuleCreateView,
    SupplierMailboxRuleDeleteView,
    SupplierMailboxRuleListView,
    SupplierMailboxRuleUpdateView,
)
from .views_imports import (
    _import_board_redirect,
    ImportDeleteBulkView,
    ImportDeleteView,
    ImportDetailView,
    ImportDetailedLogsView,
    ImportSettingsView,
    ImportWizardView,
    StuckEmailImportRunsView,
    SupplierEmailBackfillBulkView,
    SupplierEmailBackfillView,
    SupplierEmailImportAllView,
    SupplierEmailImportCancelView,
    SupplierEmailImportStatusAllView,
    SupplierEmailImportStatusView,
    SupplierEmailImportView,
    SupplierImportView,
    SupplierMappingPreviewView,
    SupplierPriceSourceCreateView,
    SupplierPriceSourceDeleteView,
    SupplierPriceSourceImportView,
    SupplierPriceReimportAllView,
    SupplierQuickUploadView,
    SupplierRatesRecalculateView,
)
from .views_our_products import (
    CatalogueLinkingAIAdviceView,
    CatalogueLinkingAIAdviceReviewView,
    CatalogueLinkingCandidateView,
    CatalogueLinkingWorkbenchView,
    FragranticaProductReviewView,
    FragranticaProductLinkView,
    FragranticaProductUnlinkView,
    OurProductCreateView,
    OurProductDeleteView,
    OurProductDetailView,
    OurProductListView,
    OurProductUpdateView,
    OurProductVariantInlineUpdateView,
)
from .views_currency import (
    CurrencyRateBulkDeleteView,
    CurrencyRateDeleteView,
    CurrencyRateUpdateView,
    CurrencyRateView,
)
from .views_shell import DashboardView, DocumentationView
from .views_supplier_products import (
    SupplierProductBulkDeleteView,
    SupplierProductCleanupView,
    SupplierProductCreateView,
    SupplierProductDeleteView,
    SupplierProductDetailView,
    SupplierProductInactiveCleanupView,
    SupplierProductLinkView,
    SupplierProductListView,
    SupplierProductSearchView,
    SupplierProductUpdateView,
    ViewerProductDetailView,
    ViewerProductListView,
    ViewerProductSearchView,
)
from .views_product_linking import (
    ProductLinkingApplyView,
    ProductLinkingSearchView,
    ProductLinkingView,
)
