# Generated by Django 5.0.14 on 2026-01-11 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('imap', 'IMAP'), ('pop3', 'POP3')], default='imap', max_length=10)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('host', models.CharField(max_length=200)),
                ('port', models.PositiveIntegerField(default=993)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('use_ssl', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD')], default='RUB', max_length=3)),
                ('from_address_pattern', models.CharField(blank=True, max_length=200)),
                ('price_subject_pattern', models.CharField(blank=True, max_length=200)),
                ('price_filename_pattern', models.CharField(blank=True, max_length=200)),
                ('stock_subject_pattern', models.CharField(blank=True, max_length=200)),
                ('stock_filename_pattern', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField()),
                ('from_currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD')], max_length=3)),
                ('to_currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD')], max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('source', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'unique_together': {('rate_date', 'from_currency', 'to_currency')},
            },
        ),
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_kind', models.CharField(choices=[('price', 'Price'), ('stock', 'Stock')], max_length=10)),
                ('filename', models.CharField(max_length=255)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.importbatch')),
            ],
        ),
        migrations.AddField(
            model_name='importbatch',
            name='mailbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prices.mailbox'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierFileMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_kind', models.CharField(choices=[('price', 'Price'), ('stock', 'Stock')], max_length=10)),
                ('mapping_mode', models.CharField(choices=[('name', 'Column name'), ('index', 'Column index')], default='name', max_length=10)),
                ('sheet_name', models.CharField(blank=True, max_length=200)),
                ('sheet_index', models.PositiveIntegerField(blank=True, null=True)),
                ('header_row', models.PositiveIntegerField(default=1)),
                ('currency', models.CharField(blank=True, choices=[('RUB', 'RUB'), ('USD', 'USD')], max_length=3)),
                ('column_map', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierMailboxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_pattern', models.CharField(blank=True, max_length=200)),
                ('subject_pattern', models.CharField(blank=True, max_length=200)),
                ('filename_pattern', models.CharField(blank=True, max_length=200)),
                ('match_price_files', models.BooleanField(default=True)),
                ('match_stock_files', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.mailbox')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_sku', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=300)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD')], default='RUB', max_length=3)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('last_imported_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.supplier')),
            ],
            options={
                'unique_together': {('supplier', 'supplier_sku')},
            },
        ),
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prices.importbatch')),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.supplierproduct')),
            ],
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD')], max_length=3)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prices.importbatch')),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.supplierproduct')),
            ],
        ),
    ]
