# Generated by Django 5.0.14 on 2026-01-11 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='imports/'),
        ),
        migrations.AddField(
            model_name='importfile',
            name='mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prices.supplierfilemapping'),
        ),
    ]
