# Generated by Django 5.0.14 on 2026-01-11 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_importfile_file_importfile_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='last_import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prices.importbatch'),
        ),
    ]
