# Generated by Django 5.0.14 on 2026-01-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_supplierproduct_created_import_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierfilemapping',
            name='sheet_indexes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplierfilemapping',
            name='sheet_names',
            field=models.TextField(blank=True),
        ),
    ]
