# Generated by Django 5.0.14 on 2026-01-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_supplierfilemapping_sheet_indexes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='stock_filename_pattern',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='stock_subject_pattern',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='default_currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD')], default='USD', max_length=3),
        ),
    ]
