# Generated by Django 5.0.14 on 2026-01-11 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0006_remove_supplier_stock_filename_pattern_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierfilemapping',
            name='currency',
        ),
    ]
