# Generated by Django 5.0.14 on 2026-01-11 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0007_remove_supplierfilemapping_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('processed_messages', models.PositiveIntegerField(default=0)),
                ('matched_files', models.PositiveIntegerField(default=0)),
                ('processed_files', models.PositiveIntegerField(default=0)),
                ('skipped_duplicates', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('last_message', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prices.supplier')),
            ],
        ),
    ]
