# Generated by Django 5.0.14 on 2026-01-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0008_emailimportrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailimportrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='running', max_length=20),
        ),
    ]
