# Generated by Django 5.0.14 on 2026-01-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0009_alter_emailimportrun_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='email_search_days',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
