# Generated by Django 5.0.14 on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0014_importsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="importsettings",
            name="cbr_markup_percent",
            field=models.DecimalField(decimal_places=3, default=2.7, max_digits=6),
        ),
    ]
