# Generated by Django 5.0.14 on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0015_importsettings_cbr_markup_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricesnapshot",
            name="price_rub",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="pricesnapshot",
            name="price_usd",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]

