# Generated by Django 5.0.14 on 2026-02-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0017_importsettings_cbr_markup_default_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsettings',
            name='filename_blacklist_terms',
            field=models.TextField(
                blank=True,
                default='\u0441\u0432\u0435\u0440\u043a\u0430\n\u043d\u0430\u043a\u043b\u0430\u0434\u043d\u0430\u044f\ninvoice\n\u0430\u043a\u0442\nreport\n\u043d\u0430\u043a\u043b',
            ),
        ),
    ]
