# Generated by Django 5.0.14 on 2026-02-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0018_importsettings_filename_blacklist_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsettings',
            name='auto_mark_seen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='importsettings',
            name='max_messages_per_run',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
