# Generated by Django 5.0.14 on 2026-02-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0019_importsettings_auto_mark_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsettings',
            name='supplier_batch_offset',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importsettings',
            name='supplier_batch_size',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
