# Generated by Django 5.0.14 on 2026-02-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0020_importsettings_supplier_batch_offset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='last_email_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_email_errors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_email_last_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_email_mailboxes',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_email_matched',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_email_processed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
