# Generated by Django 5.0.14 on 2026-02-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0024_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailimportrun',
            name='detailed_log',
            field=models.TextField(blank=True),
        ),
    ]
