# Generated by Django 5.0.14 on 2026-02-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0025_emailimportrun_detailed_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsettings',
            name='deactivate_products_after_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
