# Generated by Django 5.0.14 on 2026-02-22 19:19

import prices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0026_importsettings_deactivate_products_after_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=prices.models.import_file_upload_to),
        ),
    ]
