# Generated by Django 5.0.14 on 2026-03-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0027_alter_importfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=100),
        ),
    ]
