# Generated by Django 5.0.14 on 2026-03-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0028_mailbox_priority'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pricesnapshot',
            index=models.Index(fields=['supplier_product', '-recorded_at'], name='prices_pric_supplie_ceab44_idx'),
        ),
        migrations.AddIndex(
            model_name='pricesnapshot',
            index=models.Index(fields=['supplier_product', 'recorded_at'], name='prices_pric_supplie_1e254e_idx'),
        ),
    ]
