# Generated by Django 5.0.14 on 2026-03-14 10:50

from django.db import migrations, models


def _create_pg_trgm_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS prices_sp_name_trgm_idx
            ON prices_supplierproduct
            USING gin (name gin_trgm_ops);
            """
        )
        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS prices_supplier_name_trgm_idx
            ON prices_supplier
            USING gin (name gin_trgm_ops);
            """
        )


def _drop_pg_trgm_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP INDEX IF EXISTS prices_sp_name_trgm_idx;")
        cursor.execute("DROP INDEX IF EXISTS prices_supplier_name_trgm_idx;")


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0029_pricesnapshot_prices_pric_supplie_ceab44_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='supplierproduct',
            index=models.Index(fields=['name'], name='prices_sp_name_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierproduct',
            index=models.Index(fields=['supplier_sku'], name='prices_sp_sku_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierproduct',
            index=models.Index(fields=['is_active', 'supplier'], name='prices_sp_active_supplier_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierproduct',
            index=models.Index(fields=['is_active', 'current_price'], name='prices_sp_active_price_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierproduct',
            index=models.Index(fields=['is_active', 'last_imported_at'], name='prices_sp_active_lastimp_idx'),
        ),
        migrations.RunPython(_create_pg_trgm_indexes, _drop_pg_trgm_indexes),
    ]
