# Generated by Django 5.1.11 on 2026-04-24 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('prices', '0033_supplier_expected_import_interval_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='catalog_perfume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_products', to='catalog.perfume'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='catalog_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_products', to='catalog.perfumevariant'),
        ),
    ]
