# Generated by Codex on 2026-04-25

from django.db import migrations, models


def update_default_supplier_cadence(apps, schema_editor):
    Supplier = apps.get_model("prices", "Supplier")
    Supplier.objects.filter(expected_import_interval_hours=72).update(
        expected_import_interval_hours=24
    )


def restore_default_supplier_cadence(apps, schema_editor):
    Supplier = apps.get_model("prices", "Supplier")
    Supplier.objects.filter(expected_import_interval_hours=24).update(
        expected_import_interval_hours=72
    )


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0034_supplierproduct_catalog_perfume_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="message_folder",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="expected_import_interval_hours",
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.RunPython(
            update_default_supplier_cadence,
            reverse_code=restore_default_supplier_cadence,
        ),
    ]
