# Generated by Django 5.1.11 on 2026-04-25 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0035_business_day_supplier_cadence'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='quarantine_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importfile',
            name='reason_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='importfile',
            name='storage_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('quarantine', 'Quarantine')], default='permanent', max_length=20),
        ),
        migrations.AddField(
            model_name='importsettings',
            name='minimum_price_rows',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='importsettings',
            name='quarantine_retention_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='importsettings',
            name='skipped_attachment_storage',
            field=models.CharField(default='log_only', max_length=20),
        ),
        migrations.CreateModel(
            name='EmailAttachmentDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_folder', models.CharField(blank=True, max_length=255)),
                ('message_uid', models.CharField(blank=True, max_length=64)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('message_date', models.DateTimeField(blank=True, null=True)),
                ('sender', models.CharField(blank=True, max_length=300)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=200)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('decision', models.CharField(choices=[('imported', 'Imported'), ('duplicate', 'Duplicate'), ('skipped', 'Skipped'), ('failed', 'Failed'), ('quarantined', 'Quarantined')], max_length=30)),
                ('reason_code', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prices.importbatch')),
                ('import_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prices.importfile')),
                ('mailbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prices.mailbox')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prices.emailimportrun')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prices.supplier')),
            ],
            options={
                'indexes': [models.Index(fields=['supplier', '-created_at'], name='prices_diag_supplier_idx'), models.Index(fields=['reason_code', '-created_at'], name='prices_diag_reason_idx'), models.Index(fields=['decision', '-created_at'], name='prices_diag_decision_idx'), models.Index(fields=['mailbox', '-created_at'], name='prices_diag_mailbox_idx')],
            },
        ),
    ]
