# Generated by Codex on 2026-04-25

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0036_import_diagnostics_quarantine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailbox",
            name="password",
            field=encrypted_fields.fields.EncryptedCharField(max_length=200),
        ),
    ]
