# Generated by Codex on 2026-04-25

from django.db import migrations, transaction


def reencrypt_mailbox_passwords(apps, schema_editor):
    Mailbox = apps.get_model("prices", "Mailbox")
    batch_size = 500
    last_pk = 0

    while True:
        mailbox_ids = list(
            Mailbox.objects.filter(pk__gt=last_pk)
            .order_by("pk")
            .values_list("pk", flat=True)[:batch_size]
        )
        if not mailbox_ids:
            break

        with transaction.atomic():
            for mailbox in Mailbox.objects.filter(pk__in=mailbox_ids).order_by("pk"):
                # Reading returns plaintext for legacy values and decrypted text for tokens.
                # Saving writes exactly one encrypted token, so the migration is idempotent.
                mailbox.password = mailbox.password
                mailbox.save(update_fields=["password"])

        last_pk = mailbox_ids[-1]


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0037_alter_mailbox_password_encrypted"),
    ]

    operations = [
        migrations.RunPython(reencrypt_mailbox_passwords, migrations.RunPython.noop),
    ]
