# Generated by Codex on 2026-04-25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0038_reencrypt_mailbox_passwords"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailimportrun",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
