# Generated by Django 5.1.11 on 2026-04-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0039_emailimportrun_updated_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('message_id__isnull', False), models.Q(('message_id', ''), _negated=True)), fields=('mailbox', 'message_id'), name='uniq_batch_mailbox_message_id'),
        ),
    ]
