# Generated by Codex on 2026-04-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0040_importbatch_uniq_batch_mailbox_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailattachmentdiagnostic",
            name="reason_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name="SupplierPriceSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("email_link", "Email link"),
                            ("fixed_link", "Fixed link"),
                        ],
                        default="fixed_link",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("auto", "Auto detect"),
                            ("yandex_disk", "Yandex Disk"),
                            ("google_drive", "Google Drive"),
                            ("direct_url", "Direct URL"),
                            ("mailru_cloud", "Mail.ru Cloud"),
                        ],
                        default="auto",
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=1000)),
                (
                    "url_pattern",
                    models.CharField(
                        blank=True,
                        help_text="Optional text that must be present in email links.",
                        max_length=300,
                    ),
                ),
                (
                    "file_pattern",
                    models.CharField(
                        blank=True,
                        help_text="Optional filename text filter inside folders.",
                        max_length=200,
                    ),
                ),
                (
                    "pick_rule",
                    models.CharField(
                        choices=[
                            ("newest_valid", "Newest valid file"),
                            ("first_valid", "First valid file"),
                        ],
                        default="newest_valid",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_status", models.CharField(blank=True, max_length=30)),
                ("last_message", models.TextField(blank=True)),
                ("last_filename", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_sources",
                        to="prices.supplier",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="supplierpricesource",
            index=models.Index(
                fields=["supplier", "source_type", "is_active"],
                name="prices_supp_supplie_e44a77_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supplierpricesource",
            index=models.Index(
                fields=["source_type", "is_active"],
                name="prices_supp_source__df0aa9_idx",
            ),
        ),
    ]
