# Generated by Django 5.2.13 on 2026-04-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0041_supplier_price_sources"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="emailimportrun",
            index=models.Index(
                fields=["supplier", "-started_at"], name="prices_eir_sup_start_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailimportrun",
            index=models.Index(
                fields=["status", "-updated_at"], name="prices_eir_status_updated_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["supplier", "status", "-created_at"],
                name="prices_ib_supplier_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["status", "-received_at"], name="prices_ib_status_received_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importfile",
            index=models.Index(
                fields=["status", "file_kind"], name="prices_if_status_kind_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importfile",
            index=models.Index(
                fields=["import_batch", "file_kind", "status"],
                name="prices_if_batch_kind_stat_idx",
            ),
        ),
    ]
