from django.urls import path

from . import views


app_name = "assistant_core"

urlpatterns = [
    path("", views.DashboardView.as_view(), name="dashboard"),
    path("knowledge/", views.KnowledgeView.as_view(), name="knowledge"),
    path("rules/", views.RulesView.as_view(), name="rules"),
    path("aliases/", views.AliasesView.as_view(), name="aliases"),
    path("aliases/brands/new/", views.BrandAliasCreateView.as_view(), name="brand_alias_create"),
    path("aliases/brands/<int:pk>/edit/", views.BrandAliasUpdateView.as_view(), name="brand_alias_update"),
    path("aliases/brands/<int:pk>/delete/", views.BrandAliasDeleteView.as_view(), name="brand_alias_delete"),
    path("aliases/products/new/", views.ProductAliasCreateView.as_view(), name="product_alias_create"),
    path("aliases/products/<int:pk>/edit/", views.ProductAliasUpdateView.as_view(), name="product_alias_update"),
    path("aliases/products/<int:pk>/delete/", views.ProductAliasDeleteView.as_view(), name="product_alias_delete"),
    path("aliases/concentrations/new/", views.ConcentrationAliasCreateView.as_view(), name="concentration_alias_create"),
    path("aliases/concentrations/<int:pk>/edit/", views.ConcentrationAliasUpdateView.as_view(), name="concentration_alias_update"),
    path("aliases/concentrations/<int:pk>/delete/", views.ConcentrationAliasDeleteView.as_view(), name="concentration_alias_delete"),
    path("rules/global/new/", views.GlobalRuleCreateView.as_view(), name="global_rule_create"),
    path("rules/supplier/new/", views.SupplierRuleCreateView.as_view(), name="supplier_rule_create"),
    path("knowledge/notes/new/", views.KnowledgeNoteCreateView.as_view(), name="knowledge_note_create"),
    path("rules/<str:model_name>/<int:pk>/disable/", views.RuleDisableView.as_view(), name="rule_disable"),
    path("rules/teach-from-decision/", views.TeachFromDecisionView.as_view(), name="teach_from_decision"),
    path("catalog/brands/", views.CatalogBrandListView.as_view(), name="catalog_brands"),
    path("catalog/brands/new/", views.CatalogBrandCreateView.as_view(), name="catalog_brand_create"),
    path("catalog/brands/<int:pk>/edit/", views.CatalogBrandUpdateView.as_view(), name="catalog_brand_update"),
    path("catalog/brands/<int:pk>/delete/", views.CatalogBrandDeleteView.as_view(), name="catalog_brand_delete"),
    path("catalog/perfumes/", views.CatalogPerfumeListView.as_view(), name="catalog_perfumes"),
    path("catalog/perfumes/new/", views.CatalogPerfumeCreateView.as_view(), name="catalog_perfume_create"),
    path("catalog/perfumes/<int:pk>/edit/", views.CatalogPerfumeUpdateView.as_view(), name="catalog_perfume_update"),
    path("catalog/perfumes/<int:pk>/delete/", views.CatalogPerfumeDeleteView.as_view(), name="catalog_perfume_delete"),
    path("catalog/variants/", views.CatalogVariantListView.as_view(), name="catalog_variants"),
    path("catalog/variants/new/", views.CatalogVariantCreateView.as_view(), name="catalog_variant_create"),
    path("catalog/variants/<int:pk>/edit/", views.CatalogVariantUpdateView.as_view(), name="catalog_variant_update"),
    path("catalog/variants/<int:pk>/delete/", views.CatalogVariantDeleteView.as_view(), name="catalog_variant_delete"),
    path("catalog/import/", views.CatalogImportView.as_view(), name="catalog_import"),
    path("catalog/cleanup/", views.CatalogCleanupView.as_view(), name="catalog_cleanup"),
    path("catalog/cleanup/merge-brand/", views.CatalogBrandMergeView.as_view(), name="catalog_brand_merge"),
    path("catalog/cleanup/merge-perfume/", views.CatalogPerfumeMergeView.as_view(), name="catalog_perfume_merge"),
    path("brand-managers/", views.BrandWatchProfileListView.as_view(), name="brand_manager_list"),
    path("brand-managers/new/", views.BrandWatchProfileCreateView.as_view(), name="brand_manager_create"),
    path("brand-managers/<int:pk>/", views.BrandWatchProfileDetailView.as_view(), name="brand_manager_detail"),
    path("brand-managers/<int:pk>/run-mock/", views.RunMockBrandWatchView.as_view(), name="brand_manager_run_mock"),
    path("research/jobs/", views.ResearchJobListView.as_view(), name="research_jobs"),
    path("research/jobs/<int:pk>/", views.ResearchJobDetailView.as_view(), name="research_job_detail"),
    path("research/changes/<int:pk>/<str:status>/", views.DetectedChangeStatusView.as_view(), name="detected_change_status"),
    path("research/claims/", views.ClaimListView.as_view(), name="claims"),
    path("research/claims/<int:pk>/<str:status>/", views.ClaimStatusView.as_view(), name="claim_status"),
    path("research/drafts/", views.DraftListView.as_view(), name="drafts"),
    path("research/drafts/<int:pk>/<str:status>/", views.DraftStatusView.as_view(), name="draft_status"),
    path("research/perfume/<int:pk>/", views.PerfumeResearchView.as_view(), name="perfume_research"),
    path("research/perfume/<int:perfume_id>/generate-draft/", views.GenerateDraftView.as_view(), name="generate_draft"),
]
