from __future__ import annotations

from assistant_core.view_mixins import StaffAssistantMixin as StaffAssistantMixin
from assistant_core.views_catalog import (
    CatalogBrandCreateView as CatalogBrandCreateView,
    CatalogBrandDeleteView as CatalogBrandDeleteView,
    CatalogBrandListView as CatalogBrandListView,
    CatalogBrandMergeView as CatalogBrandMergeView,
    CatalogBrandUpdateView as CatalogBrandUpdateView,
    CatalogCleanupView as CatalogCleanupView,
    CatalogContextMixin as CatalogContextMixin,
    CatalogImportView as CatalogImportView,
    CatalogPerfumeCreateView as CatalogPerfumeCreateView,
    CatalogPerfumeDeleteView as CatalogPerfumeDeleteView,
    CatalogPerfumeListView as CatalogPerfumeListView,
    CatalogPerfumeMergeView as CatalogPerfumeMergeView,
    CatalogPerfumeUpdateView as CatalogPerfumeUpdateView,
    CatalogVariantCreateView as CatalogVariantCreateView,
    CatalogVariantDeleteView as CatalogVariantDeleteView,
    CatalogVariantListView as CatalogVariantListView,
    CatalogVariantUpdateView as CatalogVariantUpdateView,
)
from assistant_core.views_dashboard import DashboardView as DashboardView
from assistant_core.views_knowledge import (
    AliasesView as AliasesView,
    AliasManageMixin as AliasManageMixin,
    BrandAliasCreateView as BrandAliasCreateView,
    BrandAliasDeleteView as BrandAliasDeleteView,
    BrandAliasUpdateView as BrandAliasUpdateView,
    ConcentrationAliasCreateView as ConcentrationAliasCreateView,
    ConcentrationAliasDeleteView as ConcentrationAliasDeleteView,
    ConcentrationAliasUpdateView as ConcentrationAliasUpdateView,
    GarbageKeywordCreateView as GarbageKeywordCreateView,
    GlobalRuleCreateView as GlobalRuleCreateView,
    GlobalRuleUpdateView as GlobalRuleUpdateView,
    KnowledgeNoteCreateView as KnowledgeNoteCreateView,
    KnowledgeView as KnowledgeView,
    ParserTermCreateView as ParserTermCreateView,
    ProductAliasCreateView as ProductAliasCreateView,
    ProductAliasDeleteView as ProductAliasDeleteView,
    ProductAliasUpdateView as ProductAliasUpdateView,
    RuleDisableView as RuleDisableView,
    RulesView as RulesView,
    SupplierRuleCreateView as SupplierRuleCreateView,
    TeachFromDecisionView as TeachFromDecisionView,
)
from assistant_core.views_research import (
    BrandWatchProfileCreateView as BrandWatchProfileCreateView,
    BrandWatchProfileDetailView as BrandWatchProfileDetailView,
    BrandWatchProfileListView as BrandWatchProfileListView,
    ClaimListView as ClaimListView,
    ClaimStatusView as ClaimStatusView,
    DetectedChangeStatusView as DetectedChangeStatusView,
    DraftListView as DraftListView,
    DraftStatusView as DraftStatusView,
    GenerateDraftView as GenerateDraftView,
    PerfumeResearchView as PerfumeResearchView,
    ResearchJobDetailView as ResearchJobDetailView,
    ResearchJobListView as ResearchJobListView,
    RunMockBrandWatchView as RunMockBrandWatchView,
)
