"""
Django settings for perfumex project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key
import logging
import os

# Production is safe-by-default: DEBUG now defaults to off. Set DEBUG=1 only for local development.
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_local_env_file(path: Path):
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip("'\"")
        if key:
            os.environ.setdefault(key, value)


load_local_env_file(BASE_DIR / ".env")


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = os.getenv("DEBUG", "0").lower() in {"1", "true", "yes", "on"}

SECRET_KEY = os.getenv("SECRET_KEY", "").strip()
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = get_random_secret_key()
        logging.getLogger(__name__).warning(
            "SECRET_KEY is missing; using an ephemeral dev-only key because DEBUG is enabled."
        )
    else:
        raise ImproperlyConfigured("SECRET_KEY must be set when DEBUG=False.")

FERNET_KEYS = [
    key.strip()
    for key in os.getenv("FERNET_KEYS", os.getenv("SALT_KEY", "")).split(",")
    if key.strip()
]
if not FERNET_KEYS:
    if DEBUG:
        FERNET_KEYS = ["dev-only-fernet-salt-key"]
        logging.getLogger(__name__).warning(
            "FERNET_KEYS is missing; using a dev-only encryption salt because DEBUG is enabled."
        )
    else:
        raise ImproperlyConfigured("FERNET_KEYS must be set when DEBUG=False.")
SALT_KEY = FERNET_KEYS

ALLOWED_HOSTS = [host.strip() for host in os.getenv("ALLOWED_HOSTS", "").split(",") if host.strip()]
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
if not DEBUG:
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured("ALLOWED_HOSTS must be set when DEBUG=False.")
    if not CSRF_TRUSTED_ORIGINS:
        raise ImproperlyConfigured("CSRF_TRUSTED_ORIGINS must be set when DEBUG=False.")

if not DEBUG:
    SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", False)
    SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", SECURE_SSL_REDIRECT)
    CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", SECURE_SSL_REDIRECT)
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000" if SECURE_SSL_REDIRECT else "0"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", SECURE_SSL_REDIRECT)
    SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", SECURE_SSL_REDIRECT)
    SECURE_REFERRER_POLICY = "same-origin"
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'catalog',
    'assistant_core',
    'assistant_linking',
    'prices',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'prices.middleware.ForceMoscowTimezoneMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'prices.middleware.AdminPanelStaffOnlyMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'perfumex.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'perfumex.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASE_ENGINE = os.getenv("DATABASE_ENGINE", "postgres").lower()
if DATABASE_ENGINE != "postgres":
    raise RuntimeError(
        "Unsupported DATABASE_ENGINE. This project is configured for PostgreSQL only. "
        "Set DATABASE_ENGINE=postgres."
    )

# Stray local sqlite files are ignored by runtime PostgreSQL settings and must not be committed.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "perfumex_local"),
        "USER": os.getenv("POSTGRES_USER", "postgres"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", ""),
        "HOST": os.getenv("POSTGRES_HOST", "127.0.0.1"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024  # 25 MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 2000

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "viewer_home"
LOGOUT_REDIRECT_URL = "login"

ASSISTANT_USE_OPENAI = os.getenv("ASSISTANT_USE_OPENAI", "false").lower() in {"1", "true", "yes", "on"}
OPENAI_MODEL_SUGGESTION = os.getenv("OPENAI_MODEL_SUGGESTION", "gpt-5.4-mini")
OPENAI_MODEL_RESEARCH = os.getenv("OPENAI_MODEL_RESEARCH", "gpt-5.4")
OPENAI_MODEL_WRITER = os.getenv("OPENAI_MODEL_WRITER", "gpt-5.4-mini")

LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)

_LOGGING_HANDLERS = {
    "file": {
        "class": "logging.handlers.RotatingFileHandler",
        "filename": str(LOG_DIR / "perfumex.log"),
        "maxBytes": 10 * 1024 * 1024,
        "backupCount": 5,
        "formatter": "standard",
        "level": "INFO",
    }
}
if DEBUG:
    _LOGGING_HANDLERS["stderr"] = {
        "class": "logging.StreamHandler",
        "formatter": "standard",
        "level": "ERROR",
    }

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s %(levelname)s [%(name)s] %(message)s",
        },
    },
    "handlers": _LOGGING_HANDLERS,
    "root": {
        "handlers": ["stderr"] if DEBUG else [],
        "level": "INFO",
    },
    "loggers": {
        "prices": {
            "handlers": ["file"] + (["stderr"] if DEBUG else []),
            "level": "INFO",
            "propagate": False,
        },
        "assistant_core": {
            "handlers": ["file"] + (["stderr"] if DEBUG else []),
            "level": "INFO",
            "propagate": False,
        },
        "assistant_linking": {
            "handlers": ["file"] + (["stderr"] if DEBUG else []),
            "level": "INFO",
            "propagate": False,
        },
    },
}
