from __future__ import annotations

from assistant_linking.views_linking import (
    BulkLinkStatusView as BulkLinkStatusView,
    BulkLinkView as BulkLinkView,
    GenerateSuggestionsView as GenerateSuggestionsView,
    GroupActionView as GroupActionView,
    GroupDetailView as GroupDetailView,
    GroupQueueView as GroupQueueView,
    ProductWorkbenchView as ProductWorkbenchView,
    RebuildGroupsView as RebuildGroupsView,
    UndoLinkActionView as UndoLinkActionView,
)
from assistant_linking.views_normalization import (
    AcceptCatalogCandidateView as AcceptCatalogCandidateView,
    BagListView as BagListView,
    CosmeticListView as CosmeticListView,
    DeodorantListView as DeodorantListView,
    ExcludeGarbageKeywordView as ExcludeGarbageKeywordView,
    GarbageListView as GarbageListView,
    LockParseView as LockParseView,
    LowConfidenceListView as LowConfidenceListView,
    ManualReviewListView as ManualReviewListView,
    MissingBrandListView as MissingBrandListView,
    MissingConcentrationListView as MissingConcentrationListView,
    MissingNameListView as MissingNameListView,
    MissingSizeListView as MissingSizeListView,
    ModifierConflictListView as ModifierConflictListView,
    NormalizationDashboardView as NormalizationDashboardView,
    NormalizationIssueListView as NormalizationIssueListView,
    NormalizationSearchMixin as NormalizationSearchMixin,
    ParsedListView as ParsedListView,
    ParsedProductDetailView as ParsedProductDetailView,
    ReparseProductView as ReparseProductView,
    SaveBrandAliasView as SaveBrandAliasView,
    SaveProductAliasView as SaveProductAliasView,
    SetListView as SetListView,
    TeachParseView as TeachParseView,
    TesterSampleListView as TesterSampleListView,
    UnparsedListView as UnparsedListView,
)
