from __future__ import annotations

from assistant_linking.views_linking import (
    AILearningProposalApplyView as AILearningProposalApplyView,
    AILearningProposalBulkApplyAliasView as AILearningProposalBulkApplyAliasView,
    AILearningProposalRegeneratePreviewView as AILearningProposalRegeneratePreviewView,
    AILearningProposalRefreshParsesView as AILearningProposalRefreshParsesView,
    AILearningProposalRevertAliasView as AILearningProposalRevertAliasView,
    AIRecommendationDetailView as AIRecommendationDetailView,
    AIRecommendationPatternScanView as AIRecommendationPatternScanView,
    AIRecommendationQueueView as AIRecommendationQueueView,
    AIRecommendationReviewView as AIRecommendationReviewView,
    BulkLinkStatusView as BulkLinkStatusView,
    BulkLinkView as BulkLinkView,
    GenerateSuggestionsView as GenerateSuggestionsView,
    GroupActionView as GroupActionView,
    GroupDetailView as GroupDetailView,
    GroupQueueView as GroupQueueView,
    ProductWorkbenchView as ProductWorkbenchView,
    RebuildGroupsView as RebuildGroupsView,
    UndoLinkActionView as UndoLinkActionView,
)
from assistant_linking.views_normalization import (
    AcceptCatalogCandidateView as AcceptCatalogCandidateView,
    AtomizerListView as AtomizerListView,
    BagListView as BagListView,
    CosmeticListView as CosmeticListView,
    DecantListView as DecantListView,
    DeodorantListView as DeodorantListView,
    ExcludeGarbageKeywordView as ExcludeGarbageKeywordView,
    GarbageListView as GarbageListView,
    LockParseView as LockParseView,
    LowConfidenceListView as LowConfidenceListView,
    ManualReviewListView as ManualReviewListView,
    MissingBrandListView as MissingBrandListView,
    MissingConcentrationListView as MissingConcentrationListView,
    MissingNameListView as MissingNameListView,
    MissingSizeListView as MissingSizeListView,
    ModifierConflictListView as ModifierConflictListView,
    NormalizationDashboardView as NormalizationDashboardView,
    NormalizationIssueListView as NormalizationIssueListView,
    NormalizationSearchMixin as NormalizationSearchMixin,
    ParseUnparsedProductsView as ParseUnparsedProductsView,
    ParsedListView as ParsedListView,
    ParsedProductDetailView as ParsedProductDetailView,
    RefreshVisibleParsesView as RefreshVisibleParsesView,
    ReparseProductView as ReparseProductView,
    SaveBrandAliasView as SaveBrandAliasView,
    SaveProductAliasView as SaveProductAliasView,
    SetListView as SetListView,
    TeachParseView as TeachParseView,
    TesterSampleListView as TesterSampleListView,
    UnparsedListView as UnparsedListView,
    VintageListView as VintageListView,
)
