# Generated by Django 5.1.11 on 2026-04-24 11:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=160, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=120)),
                ('official_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=160, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('family', models.CharField(blank=True, db_index=True, max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True)),
                ('concentration', models.CharField(blank=True, db_index=True, max_length=80)),
                ('audience', models.CharField(blank=True, db_index=True, max_length=80)),
                ('collection_name', models.CharField(blank=True, db_index=True, max_length=180)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('perfumer_name', models.CharField(blank=True, db_index=True, max_length=220)),
                ('country_of_manufacture', models.CharField(blank=True, max_length=120)),
                ('verification_status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Needs review'), ('verified', 'Verified'), ('conflict', 'Conflict')], db_index=True, default='review', max_length=24)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('summary_short', models.TextField(blank=True)),
                ('summary_long', models.TextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfumes', to='catalog.brand')),
            ],
            options={
                'ordering': ('brand__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AIDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_type', models.CharField(db_index=True, default='description', max_length=40)),
                ('source_claims_json', models.JSONField(default=list)),
                ('content_json', models.JSONField(default=dict)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('prompt_version', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('needs_edits', 'Needs edits'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('warnings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_drafts', to='catalog.perfume')),
            ],
        ),
        migrations.CreateModel(
            name='PerfumeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size_ml', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=7, null=True)),
                ('size_label', models.CharField(blank=True, max_length=80)),
                ('packaging', models.CharField(blank=True, db_index=True, max_length=80)),
                ('variant_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('is_tester', models.BooleanField(db_index=True, default=False)),
                ('ean', models.CharField(blank=True, db_index=True, max_length=64)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.perfume')),
            ],
            options={
                'ordering': ('perfume__brand__name', 'perfume__name', 'size_ml'),
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(db_index=True, default='other', max_length=40)),
                ('source_domain', models.CharField(blank=True, db_index=True, max_length=160)),
                ('priority_rank', models.PositiveSmallIntegerField(default=50)),
                ('reliability', models.CharField(db_index=True, default='medium', max_length=20)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_checked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('perfume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='catalog.perfume')),
            ],
            options={
                'ordering': ('priority_rank', 'url'),
            },
        ),
        migrations.CreateModel(
            name='PerfumeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('top', 'Top'), ('middle', 'Middle'), ('base', 'Base'), ('general', 'General')], db_index=True, default='general', max_length=20)),
                ('confidence', models.CharField(db_index=True, default='medium', max_length=20)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfume_notes', to='catalog.note')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfume_notes', to='catalog.perfume')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.source')),
            ],
        ),
        migrations.CreateModel(
            name='PerfumeAccord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.PositiveSmallIntegerField(default=50)),
                ('accord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfume_accords', to='catalog.accord')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfume_accords', to='catalog.perfume')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.source')),
            ],
        ),
        migrations.CreateModel(
            name='FactClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(db_index=True, max_length=64)),
                ('value_json', models.JSONField(default=dict)),
                ('confidence', models.CharField(db_index=True, default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('conflict', 'Conflict')], db_index=True, default='pending', max_length=20)),
                ('claim_hash', models.CharField(db_index=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_claims', to='catalog.perfume')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_claims', to='catalog.source')),
            ],
        ),
        migrations.AddIndex(
            model_name='perfume',
            index=models.Index(fields=['brand', 'name'], name='catalog_per_brand_i_d03309_idx'),
        ),
        migrations.AddIndex(
            model_name='perfume',
            index=models.Index(fields=['brand', 'concentration', 'audience'], name='catalog_per_brand_i_4f8462_idx'),
        ),
        migrations.AddConstraint(
            model_name='perfumevariant',
            constraint=models.UniqueConstraint(fields=('perfume', 'size_ml', 'packaging', 'variant_type', 'is_tester'), name='uniq_catalog_perfume_variant_identity'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(fields=('perfume', 'url'), name='uniq_catalog_source_perfume_url'),
        ),
        migrations.AddConstraint(
            model_name='perfumenote',
            constraint=models.UniqueConstraint(fields=('perfume', 'note', 'position', 'source'), name='uniq_catalog_perfume_note'),
        ),
        migrations.AddConstraint(
            model_name='perfumeaccord',
            constraint=models.UniqueConstraint(fields=('perfume', 'accord', 'source'), name='uniq_catalog_perfume_accord'),
        ),
        migrations.AddConstraint(
            model_name='factclaim',
            constraint=models.UniqueConstraint(fields=('perfume', 'source', 'field_name', 'claim_hash'), name='uniq_catalog_fact_claim'),
        ),
    ]
