# Generated by Django 5.2.13 on 2026-05-02 15:42

import django.db.models.deletion
import re
import unicodedata
from django.db import migrations, models
from django.utils.text import slugify


def normalized_collection_name(value):
    text = unicodedata.normalize("NFKD", value or "")
    text = "".join(char for char in text if not unicodedata.combining(char))
    text = text.replace("&", " and ").lower()
    return re.sub(r"\s+", " ", re.sub(r"[^\w]+", " ", text)).strip()


def unique_collection_slug(Collection, brand_id, value):
    base = slugify(value or "") or "collection"
    slug = base
    counter = 2
    while Collection.objects.filter(brand_id=brand_id, slug=slug).exists():
        suffix = f"-{counter}"
        slug = f"{base[:240 - len(suffix)]}{suffix}"
        counter += 1
    return slug


def backfill_perfume_collections(apps, schema_editor):
    Collection = apps.get_model("catalog", "Collection")
    Perfume = apps.get_model("catalog", "Perfume")
    perfumes = Perfume.objects.exclude(collection_name="").select_related("brand")
    collections_by_key = {
        (collection.brand_id, collection.normalized_name): collection
        for collection in Collection.objects.all()
    }
    for perfume in perfumes.iterator():
        normalized_name = normalized_collection_name(perfume.collection_name)
        if not normalized_name:
            continue
        key = (perfume.brand_id, normalized_name)
        collection = collections_by_key.get(key)
        if collection is None:
            collection = Collection.objects.create(
                brand_id=perfume.brand_id,
                name=perfume.collection_name,
                normalized_name=normalized_name,
                slug=unique_collection_slug(
                    Collection, perfume.brand_id, perfume.collection_name
                ),
            )
            collections_by_key[key] = collection
        Perfume.objects.filter(pk=perfume.pk).update(collection_id=collection.pk)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_expand_concentration_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=180)),
                (
                    "normalized_name",
                    models.CharField(blank=True, db_index=True, max_length=220),
                ),
                ("slug", models.SlugField(blank=True, max_length=240)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to="catalog.brand",
                    ),
                ),
            ],
            options={
                "ordering": ("brand__name", "name"),
            },
        ),
        migrations.AddField(
            model_name="perfume",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="perfumes",
                to="catalog.collection",
            ),
        ),
        migrations.RunPython(backfill_perfume_collections, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                fields=("brand", "normalized_name"),
                name="uniq_catalog_collection_brand_normalized",
            ),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                fields=("brand", "slug"), name="uniq_catalog_collection_brand_slug"
            ),
        ),
    ]
