# Generated by Django 5.1.11 on 2026-04-24 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('prices', '0034_supplierproduct_catalog_perfume_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandWatchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('official_url', models.URLField(blank=True)),
                ('trusted_sources_json', models.JSONField(blank=True, default=list)),
                ('watch_frequency', models.CharField(db_index=True, default='weekly', max_length=40)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('instructions', models.TextField(blank=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch_profile', to='catalog.brand')),
            ],
            options={
                'ordering': ('brand__name',),
            },
        ),
        migrations.CreateModel(
            name='DetectedChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(db_index=True, max_length=60)),
                ('field_name', models.CharField(blank=True, db_index=True, max_length=80)),
                ('old_value_json', models.JSONField(blank=True, default=dict)),
                ('new_value_json', models.JSONField(blank=True, default=dict)),
                ('explanation', models.TextField(blank=True)),
                ('confidence', models.PositiveSmallIntegerField(db_index=True, default=50)),
                ('source_urls_json', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_research', 'Needs more research')], db_index=True, default='pending', max_length=24)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_changes', to='assistant_core.brandwatchprofile')),
                ('perfume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.perfume')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GlobalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=220)),
                ('rule_kind', models.CharField(db_index=True, max_length=60)),
                ('scope_type', models.CharField(db_index=True, max_length=60)),
                ('scope_value', models.CharField(blank=True, db_index=True, max_length=220)),
                ('rule_text', models.TextField()),
                ('examples_json', models.JSONField(blank=True, default=list)),
                ('priority', models.IntegerField(db_index=True, default=100)),
                ('confidence', models.PositiveSmallIntegerField(db_index=True, default=70)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('approved', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('priority', 'title'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(db_index=True, max_length=80)),
                ('title', models.CharField(db_index=True, max_length=220)),
                ('content', models.TextField()),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('perfume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.perfume')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prices.supplier')),
            ],
            options={
                'ordering': ('category', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ResearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(db_index=True, max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('query', models.TextField(blank=True)),
                ('context_json', models.JSONField(blank=True, default=dict)),
                ('result_summary', models.TextField(blank=True)),
                ('raw_result_json', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('perfume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.perfume')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SupplierRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=220)),
                ('rule_kind', models.CharField(db_index=True, max_length=60)),
                ('applies_to_text', models.CharField(blank=True, db_index=True, max_length=220)),
                ('rule_text', models.TextField()),
                ('examples_json', models.JSONField(blank=True, default=list)),
                ('priority', models.IntegerField(db_index=True, default=100)),
                ('confidence', models.PositiveSmallIntegerField(db_index=True, default=70)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('approved', models.BooleanField(db_index=True, default=False)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_rules', to='prices.supplier')),
            ],
            options={
                'ordering': ('supplier__name', 'priority', 'title'),
            },
        ),
        migrations.CreateModel(
            name='SourceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(db_index=True, max_length=60)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_summary', models.TextField(blank=True)),
                ('raw_facts_json', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(db_index=True)),
                ('fetch_status', models.CharField(db_index=True, default='ok', max_length=40)),
                ('brand_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_snapshots', to='assistant_core.brandwatchprofile')),
            ],
            options={
                'ordering': ('-checked_at',),
                'constraints': [models.UniqueConstraint(fields=('brand_profile', 'url', 'content_hash'), name='uniq_assistant_source_snapshot')],
            },
        ),
    ]
